<template>
    <div class="flex p-8 w-full bg-gray-200">
        <div class="container w-2/5 mx-auto space-y-4">
            <h1 class="text-3xl font-light">My account</h1>

            <!-- Profile -->
            <div class="p-6 shadow bg-white rounded space-y-6">
                <h2 class="text-xl font-light">Profile</h2>
                
                <p>Username: {{ profile.username }}</p>

                <p>Email: {{ profile.email }}</p>
                <button @click="verifyEmail" class="block p-3 rounded bg-orange-500" v-if="!profile.email_verified">Resend verification email</button>
            </div>

            <!-- Security -->
            <div class="p-6 shadow bg-white rounded space-y-6">
                <h2 class="text-xl font-light">Security</h2>
                
                <p>When using the Feirm Platform, two-factor authentication is mandatory. We allow you to login through a magic link sent to your email, or through a code generated by an OTP app such as Google Authenticator.</p>

                <p>Password: •••••••••••</p>
                <p>Two Factor Authentication: {{ determineTwoFactor(profile.two_factor_method) }}</p>
            </div>

            <!-- Logout -->
            <div class="p-6 shadow bg-white rounded space-y-6">
                <h2 class="text-xl font-light">Logout</h2>
                
                <p>When using a shared device, it is recommended for you to log out before leaving.</p>
                <button @click="logout" class="block p-3 w-28 rounded bg-red-500 text-white">Logout</button>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import authService from '@/service/api/authService';
import { defineComponent } from 'vue'

export default defineComponent({
    data() {
        return {
            profile: {} as any
        }
    },
    async mounted() {
        await authService.GetAccount().then(res => {
            this.profile = res.data;
        })
    },
    methods: {
        async verifyEmail() {
            // Resend an email confirmation to the user
            try {
                await authService.ResendEmailVerification();
                return this.$toast.success("Please check your email and verify your account.")
            } catch(e) {
                return this.$toast.error(e.response.data.error);
            }
        },

        // Based on the method used, return a pretty string
        determineTwoFactor(method: string) {
            if (method === "email") {
                return "Email magic-link"
            } else if (method === "totp") {
                return "TOTP"
            } else {
                return "Unknown"
            }
        }
    }
})
</script>
