<template>
    <div class="flex p-3 md:p-8 w-full bg-gray-200">
        <div class="container md:w-2/5 mx-auto space-y-4">
            <h1 class="text-3xl font-light">My account</h1>

            <!-- Profile -->
            <div class="p-6 shadow bg-white rounded space-y-3">
                <h2 class="text-xl font-light">Profile</h2>
                
                <p>Username: {{ profile.username }}</p>

                <p v-if="profile.email">Email: {{ profile.email }}</p>
                <button v-show="profile.email" @click="verifyEmail" class="block p-3 rounded bg-orange-500" v-if="!profile.email_verified">Resend verification email</button>
            </div>

            <!-- Security -->
            <div class="p-6 shadow bg-white rounded space-y-3">
                <h2 class="text-xl font-light">Security</h2>
                
                <p>When using the Feirm Platform, two-factor authentication is mandatory. We allow you to login through a magic link sent to your email, or through a code generated by an OTP app such as Google Authenticator.</p>

                <p>Password: •••••••••••</p>
                <p>Two Factor Authentication: {{ determineTwoFactor(profile.two_factor_method) }}</p>

                <button @click="showModal = !showModal" class="block p-3 w-28 rounded bg-orange-500 text-white">Edit</button>
            </div>

            <!-- Device security -->
            <div class="p-6 shadow bg-white rounded space-y-3">
                <h2 class="text-xl font-light">Device security</h2>
                <p>It can be an inconvenience having to login to your Feirm account every time you open the app. By saving your account key to this device, you can skip the login step when you next open the app.</p>
                <button class="block p-2 rounded text-sm font-medium text-yellow-900 bg-orange-500 hover:bg-orange-400" @click="showDeviceSecurityModal = !showDeviceSecurityModal">Save root key to device</button>
            </div>
            
            <confirm-modal
                v-if="showDeviceSecurityModal"
                heading="Save account key to device?"
                message="You are about to save your account key to this device. Please confirm this action."
                @confirmEvent="saveRootKey"
                @close="showDeviceSecurityModal = false"
            ></confirm-modal>

            <!-- Deletion -->
            <div class="p-6 shadow bg-white rounded space-y-6">
                <h2 class="text-xl font-light">Account deletion</h2>
                <p>Delete your Feirm account and all data associated to it. All of your data will be wiped immediately from our production servers, so there is no going back! We maintain rolling backups for 7 days, so your data could remain in these backups until then.</p>
                <button @click="deleteAccount" class="block p-3 w-48 rounded bg-red-500 text-white">Delete my Feirm account</button>
            </div>

            <!-- Logout -->
            <div class="p-6 shadow bg-white rounded space-y-6">
                <h2 class="text-xl font-light">Logout</h2>
                
                <p>When using a shared device, it is recommended for you to log out before leaving.</p>
                <button @click="logoutUser" class="block p-3 w-28 rounded bg-red-500 text-white">Logout</button>
            </div>
        </div>
    </div>

    <!-- Popup to change 2FA method -->
     <div v-if="showModal" class="flex fixed h-screen justify-center inset-0 items-center">
        <div class="z-50 md:w-1/3 relative bg-white p-8 rounded shadow-2xl">
            <div v-if="changeTwoFactor.step === 0" class="space-y-4">
                <h1 class="text-2xl">Change two-factor authentication method</h1>
                <p>When using the Feirm Platform, two-factor authentication is mandatory. We allow you to login through a magic link sent to your email, or through a code generated by an OTP app such as Google Authenticator.</p>
            
                <!-- 2FA method dropdown -->
                <p class="font-semibold">Choose two-factor authentication method:</p>

                <label class="block mt-4">
                    <select class="block w-full mt-1 rounded-md border-gray-300 shadow-sm" v-model="changeTwoFactor.selected">
                        <option disabled value="">Select two-factor method</option>
                        <option value="email">Email magic-link</option>
                        <option value="totp">TOTP (e.g. Google Authenticator or Authy)</option>
                    </select>
                </label>

                <!-- Warn when selecting different two factor method (TOTP)  -->
                <div v-if="changeTwoFactor.selected !== profile.two_factor_method && changeTwoFactor.selected == 'totp'" class="p-3 rounded bg-yellow-200">
                    <p>You are about to change the two-factor authentication method used for this account to TOTP. Be sure to back up your recovery codes when they are shown to you. Feirm cannot reset 2FA for user accounts if you lose access to your two factor device or recovery codes.</p>
                </div>

                <!-- Warn when selecting different two factor method (email)  -->
                <div v-if="changeTwoFactor.selected !== profile.two_factor_method && changeTwoFactor.selected == 'email'" class="p-3 rounded bg-yellow-200">
                    <p>You are about to disable your TOTP two-factor authentication method. As two-factor authentication is mandatory, you will have to approve your login requests through a magic-link sent to your email address. After disabling TOTP, your existing recovery codes will become invalid.</p>
                </div>

                <!-- Buttons -->
                <div class="space-x-3">
                    <button @click="nextStep()" :disabled="changeTwoFactor.selected === profile.two_factor_method" class="disabled:opacity-50 p-3 rounded shadow bg-orange-500 w-24 text-yellow-900">Next</button>
                    <button @click="closeModal()" class="p-3 rounded shadow bg-red-500 text-white w-24">Cancel</button>
                </div>
            </div>

            <!-- Enable TOTP -->
            <div v-if="changeTwoFactor.step === 1" class="space-y-4">
                <h1 class="text-2xl">Scan the QR code below into your authenticator app</h1>
                <img class="mx-auto" :src="totp.qrCode">

                <div class="border-2 border-gray-200 rounded p-2 w-2/4 text-center mx-auto">
                    <code>{{ totp.secret }}</code>
                </div>

                <!-- Enter token -->
                <label class="block">Enter six-digit token</label>
                <input
                    class="w-full border-2 border-gray-200 p-3 rounded outline-none focus:border-orange-500 transition duration-200"
                    v-model="totp.token"
                    type="text"
                    autofocus
                />

                <div class="space-x-3">
                    <button @click="submitTotp" class="p-3 rounded shadow bg-green-400 w-24 text-gray-900">Submit</button>
                    <button @click="closeModal()" class="p-3 rounded shadow bg-red-500 text-white w-24">Cancel</button>
                </div>
            </div>

            <!-- Recovery codes -->
            <div v-if="changeTwoFactor.step === 2" class="space-y-4">
                <h1 class="text-2xl">Write down your recovery codes</h1>
                <p>Please take the time now to write down your recovery codes. These are important as they can help you can access to your account if you lose your two-factor authentication device.</p>
                <p>Feirm cannot change the two-factor authentication method or recover the account on your behalf!</p>

                <div class="flex p-2 bg-gray-200 rounded justify-center text-center">
                    <div class="flex-col p-2">
                        <div v-for="(code, index) in recoveryCodes" :key="code">
                            <code v-if="index < 4">{{ code }}</code>
                        </div>
                    </div>

                    <div class="flex-col p-2">
                        <div v-for="(code, index) in recoveryCodes" :key="code">
                            <code v-if="index >= 4 && index < 8">{{ code }}</code>
                        </div>
                    </div>
                </div>

                <button @click="confirmRecovery" class="block w-full p-3 rounded shadow bg-orange-500 text-yellow-900">I have written down my recovery codes</button>
            </div>
        </div>

        <div @click="closeModal()" v-if="showModal" class="fixed inset-0 z-40 opacity-50 bg-black"></div>
    </div>
</template>

<script lang="ts">
import authService from '@/service/api/authService';
import { defineComponent } from 'vue'
import { authenticator } from "otplib";
import qrcode from "qrcode";

import { mapActions, mapGetters } from 'vuex';
import { useRouter } from 'vue-router';
import account from '@/class/account';
import bufferToHex from '@/helpers/bufferToHex';

import ConfirmModal from "@/components/ConfirmModal.vue";

export default defineComponent({
    data() {
        return {
            showModal: false,
            showDeviceSecurityModal: false,
            profile: {} as any,

            changeTwoFactor: {
                step: 0,
                selected: ""
            },

            totp: {
                qrCode: "",
                secret: "",
                token: ""
            },

            recoveryCodes: []
        }
    },
    components: {
        ConfirmModal
    },
    computed: {
        ...mapGetters(["getUsername"])
    },
    async mounted() {
        // Fetch account data
        await authService.GetAccount().then(res => {
            this.profile = res.data;
        });
    },
    methods: {
        ...mapActions(["logout"]),
        async verifyEmail() {
            // Resend an email confirmation to the user
            try {
                await authService.ResendEmailVerification();
                return this.$toast.success("Please check your email and verify your account.")
            } catch(e) {
                return this.$toast.error(e.response.data.error);
            }
        },

        // Based on the method used, return a pretty string
        determineTwoFactor(method: string) {
            if (method === "email") {
                return "Email magic-link"
            } else if (method === "totp") {
                return "TOTP"
            } else {
                return "Unknown"
            }
        },

        // Reset two factor modal
        closeModal() {
            this.showModal = false;
            this.changeTwoFactor.selected = "";
            this.changeTwoFactor.step = 0;
        },

        // Logout user
        logoutUser() {
            this.logout();
            this.router.push("/");
        },

        // Determine next step based on two-factor method chosen
        async nextStep() {
            // If the profile says TOTP is their two factor method,
            // but they have selected email, disable TOTP
            if (this.profile.two_factor_method === 'totp' && this.changeTwoFactor.selected === 'email') {
                try {
                    await authService.DisableTOTP();
                } catch (e) {
                    return this.$toast.error(e.response.data.error);
                }

                // Fetch updated profile data and close modal
                await authService.GetAccount().then(res => {
                    this.profile = res.data;
                });

                this.closeModal();
            }

            // Go to TOTP enable screen
            if (this.changeTwoFactor.selected === "totp") {
                // Generate TOTP secret
                const secret = authenticator.generateSecret(16);
                this.totp.secret = secret;

                // Generate scannable QR code
                const otpauth = authenticator.keyuri(this.getUsername, "Feirm", secret);
                this.totp.qrCode = await qrcode.toDataURL(otpauth);

                this.changeTwoFactor.step = 1;
            }
        },

        // Submit TOTP secret data
        async submitTotp() {
            try {
                await authService.EnableTOTP(this.totp.secret, this.totp.token);
            } catch (e) {
                return this.$toast.error(e.response.data.error);
            }

            // Set recovery codes
            try {
                const res = await authService.GetRecoveryCodes();
                this.recoveryCodes = res.data.codes;
            } catch (e) {
                return this.$toast.error(e.response.data.error);
            }

            // Change to recovery codes step
            this.changeTwoFactor.step = 2;
        },

        // User has confirmed they've written down their recovery codes, so fetch and update profile data
        async confirmRecovery() {
            await authService.GetAccount().then(res => {
                this.profile = res.data;
            });

            this.closeModal();
        },

        // Delete user account
        async deleteAccount() {
            try {
                await authService.DeleteAccount();
            } catch (e) {
                return this.$toast.error(e.response.data.error);
            }

            // Update Vuex state
            this.logout();

            // Push to index
            this.router.push("/");
        },

        saveRootKey() {
            const rootKey = account.getRootKey();
            localStorage.setItem("rootKey", bufferToHex(rootKey));

            this.showDeviceSecurityModal = false;
        }
    },
    setup() {
        const router = useRouter();

        return {
            router
        }
    }
})
</script>
