<template>
    <div class="flex p-8 w-full bg-gray-200">
        <div class="container w-2/5 mx-auto space-y-4">
            <h1 class="text-3xl font-light">My account</h1>

            <!-- Profile -->
            <div class="p-6 shadow bg-white rounded space-y-6">
                <h2 class="text-xl font-light">Profile</h2>
                
                <p>Username: {{ profile.username }}</p>

                <p>Email: {{ profile.email }}</p>
                <button @click="verifyEmail" class="block p-3 rounded bg-orange-500" v-if="!profile.email_verified">Resend verification email</button>
            </div>

            <!-- Security -->
            <div class="p-6 shadow bg-white rounded space-y-6">
                <h2 class="text-xl font-light">Security</h2>
                
                <p>When using the Feirm Platform, two-factor authentication is mandatory. We allow you to login through a magic link sent to your email, or through a code generated by an OTP app such as Google Authenticator.</p>

                <p>Password: •••••••••••</p>
                <p>Two Factor Authentication: {{ determineTwoFactor(profile.two_factor_method) }}</p>

                <button @click="showModal = !showModal" class="block p-3 w-28 rounded bg-orange-500 text-white">Edit</button>
            </div>

            <!-- Logout -->
            <div class="p-6 shadow bg-white rounded space-y-6">
                <h2 class="text-xl font-light">Logout</h2>
                
                <p>When using a shared device, it is recommended for you to log out before leaving.</p>
                <button @click="logout" class="block p-3 w-28 rounded bg-red-500 text-white">Logout</button>
            </div>
        </div>
    </div>

    <!-- Popup to change 2FA method -->
     <div v-if="showModal" class="flex fixed h-screen justify-center inset-0 items-center">
        <div class="z-50 md:w-1/3 relative bg-white p-8 rounded shadow-2xl space-y-4">
            <h1 class="text-xl">Change two-factor authentication method</h1>
            <p>When using the Feirm Platform, two-factor authentication is mandatory. We allow you to login through a magic link sent to your email, or through a code generated by an OTP app such as Google Authenticator.</p>
            
            <!-- 2FA method dropdown -->
            <p class="font-semibold">Choose two-factor authentication method:</p>

            <label class="block mt-4">
                <select class="block w-full mt-1 rounded-md border-gray-300 shadow-sm">
                    <option>Email magic-link</option>
                    <option>TOTP (e.g. Google Authenticator or Authy)</option>
                </select>
            </label>

            <!-- Buttons -->
            <div class="space-x-3">
                <button class="p-3 rounded shadow bg-orange-500 w-24 text-yellow-900">Next</button>
                <button @click="showModal = false" class="p-3 rounded shadow bg-red-500 text-white w-24">Cancel</button>
            </div>
        </div>

        <div @click="showModal = false" v-if="showModal" class="fixed inset-0 z-40 opacity-50 bg-black"></div>
    </div>
</template>

<script lang="ts">
import authService from '@/service/api/authService';
import { defineComponent } from 'vue'
import { authenticator } from "otplib";
import qrcode from "qrcode";

import { mapGetters } from 'vuex';

export default defineComponent({
    data() {
        return {
            showModal: false,
            profile: {} as any,

            totp: {
                qrCode: "",
                secret: "",
                token: ""
            }
        }
    },
    computed: {
        ...mapGetters(["getUsername"])
    },
    async mounted() {
        // Fetch account data
        await authService.GetAccount().then(res => {
            this.profile = res.data;
        });

        // Generate TOTP secret
        const secret = authenticator.generateSecret(16);
        this.totp.secret = secret;

        // Generate scannable QR code
        const otpauth = authenticator.keyuri(this.getUsername, "feirm.com", secret);
        this.totp.qrCode = await qrcode.toDataURL(otpauth)
    },
    methods: {
        async verifyEmail() {
            // Resend an email confirmation to the user
            try {
                await authService.ResendEmailVerification();
                return this.$toast.success("Please check your email and verify your account.")
            } catch(e) {
                return this.$toast.error(e.response.data.error);
            }
        },

        // Based on the method used, return a pretty string
        determineTwoFactor(method: string) {
            if (method === "email") {
                return "Email magic-link"
            } else if (method === "totp") {
                return "TOTP"
            } else {
                return "Unknown"
            }
        }
    }
})
</script>
